version: '3'

services:
    database:
        image: mysql:8.0.20
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "guesbook:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: main
            MYSQL_DATABASE: main
            MYSQL_USER: main
            MYSQL_PASSWORD: main
       
    redis:
        ports: [6379]
        image: redis:5-alpine
volumes:
    guesbook:
